version: '3'

services:
  mysql:
    container_name: 'adm_codeflix_mysql'
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_codeflix_network

networks:
  adm_codeflix_network: